config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new
  get '/tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get  'tasks/edit/:id', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new

  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
     @task = Task.find(params[:id])
  end


  def update
     @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

 private

  def task_params
    params.require(:task).permit(:title, :details)

  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

  <%= link_to "HomePage", tasks_path %>

app/views/tasks/index.html.erb
<h1>Here are your tasks</h1>
<ul>
  <%= link_to "Add new task", task_path(:new) %>

<% @tasks.each do |task| %>
<li>
  <% if task.completed == true %>
    [x]
  <% else %>
    [ ]
  <% end %>
  <%= link_to task.title, task_path(task) %>
    <%= link_to "delete", task_path(task), method: :delete %>
  </li>

 <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

  <%= link_to "HomePage", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h2> <%= @task.details %></h2>

<h3> <%= link_to "back to list", tasks_path %></h3>
<%= link_to "Update a task", edit_path(@task) %>